export const CATEGORY_RULES: [RegExp, string][] = [
  // Grocery
  [/TRADER JOE/i, "Grocery"],
  [/WHOLE FOODS/i, "Grocery"],
  [/SAFEWAY/i, "Grocery"],
  [/KROGER/i, "Grocery"],
  [/ALDI/i, "Grocery"],
  [/PUBLIX/i, "Grocery"],
  [/SPROUTS/i, "Grocery"],
  [/H-E-B/i, "Grocery"],
  [/WEGMANS/i, "Grocery"],
  [/FOOD LION/i, "Grocery"],
  [/PIGGLY WIGGLY/i, "Grocery"],

  // Superstore
  [/WAL-?MART/i, "Superstore"],
  [/SUPERCENTER/i, "Superstore"],
  [/FRED-?MEYER/i, "Superstore"],
  [/TARGET/i, "Superstore"],
  [/COSTCO/i, "Superstore"],
  [/SAM'?S CLUB/i, "Superstore"],

  // Restaurant / Dining
  [/MCDONALD/i, "Dining"],
  [/COFFEE/i, "Dining"],
  [/CAFE/i, "Dining"],
  [/CHIPOTLE/i, "Dining"],
  [/CHICK-FIL-A/i, "Dining"],
  [/DUNKIN/i, "Dining"],
  [/SUBWAY/i, "Dining"],
  [/PANERA/i, "Dining"],
  [/TACO BELL/i, "Dining"],
  [/WENDY'?S/i, "Dining"],
  [/BURGER KING/i, "Dining"],
  [/DOORDASH/i, "Dining"],
  [/UBER EATS/i, "Dining"],
  [/GRUBHUB/i, "Dining"],
  [/^TST\*/i, "Dining"],
  [/^SNACK\*/i, "Dining"],
  [/STARBUCKS/i, "Dining"],
  [/RAISING CANE/i, "Dining"],
  [/DAVE'?S?\s*HOT\s*CHICKEN/i, "Dining"],
  [/PIZZA/i, "Dining"],
  [/TAQUERIA/i, "Dining"],
  [/SUSHI/i, "Dining"],
  [/\bTHAI\b/i, "Dining"],
  [/\bDELI\b/i, "Dining"],
  [/BAGEL/i, "Dining"],
  [/ICE CREAM/i, "Dining"],
  [/GELATO/i, "Dining"],
  [/NOODLE/i, "Dining"],
  [/WAFFLE/i, "Dining"],
  [/KITCHEN/i, "Dining"],
  [/BAR & GRILL/i, "Dining"],
  [/ROASTER/i, "Dining"],
  [/\bMATCHA\b/i, "Dining"],
  [/JAMBA JUICE/i, "Dining"],
  [/\bBOBA\b/i, "Dining"],
  [/DONUT/i, "Dining"],
  [/ARAMARK/i, "Dining"],
  [/CHICKEN/i, "Dining"],
  [/MONTY'?S RED SAUCE/i, "Dining"],
  [/PHIN CAPH/i, "Dining"],
  [/FLEMINGS?\d/i, "Dining"],
  [/A DOPO/i, "Dining"],
  [/COOL BEANS/i, "Dining"],
  [/OLD CITY JAVA/i, "Dining"],
  [/WATCHHOUSE/i, "Dining"],
  [/JIANG NAN/i, "Dining"],
  [/LA CABRA/i, "Dining"],
  [/VAN LEEUWEN/i, "Dining"],
  [/VINNIE'?S/i, "Dining"],
  [/LOS TACOS/i, "Dining"],
  [/OOH LALA/i, "Dining"],
  [/YUM TRA/i, "Dining"],
  [/CHICHA SAN CHEN/i, "Dining"],
  [/SUPER TASTE/i, "Dining"],
  [/BRENZ/i, "Dining"],
  [/AROMA INDIAN/i, "Dining"],
  [/SQ \*REGULAR NYC/i, "Dining"],
  [/SQ \*NO PREFERENCE/i, "Dining"],
  [/SQ \*JACKS\b/i, "Dining"],
  [/RUBYS EAST VILLAGE/i, "Dining"],
  [/LIBERTY BAGELS/i, "Dining"],
  [/PIZZER/i, "Dining"],

  // Gas / Fuel
  [/SHELL OIL/i, "Gas"],
  [/CHEVRON/i, "Gas"],
  [/EXXONMOBIL/i, "Gas"],
  [/BP #/i, "Gas"],
  [/CIRCLE K/i, "Gas"],
  [/WAWA/i, "Gas"],
  [/SPEEDWAY/i, "Gas"],
  [/7-ELEVEN/i, "Gas"],
  [/BUC-?EE/i, "Gas"],

  // Rideshare / Transit
  [/UBER(?! EATS)/i, "Transit"],
  [/LYFT/i, "Transit"],
  [/PARKING/i, "Transit"],

  // Subscriptions / Streaming
  [/NETFLIX/i, "Subscription"],
  [/GYM/i, "Subscription"],
  [/SPOTIFY/i, "Subscription"],
  [/HULU/i, "Subscription"],
  [/DISNEY\+/i, "Subscription"],
  [/APPLE\.COM/i, "Subscription"],
  [/AMAZON PRIME/i, "Subscription"],
  [/HBO MAX/i, "Subscription"],
  [/YOUTUBE PREMIUM/i, "Subscription"],
  [/CLAUDE\.AI/i, "Subscription"],
  [/WMT PLUS/i, "Subscription"],

  // Shopping
  [/AMAZON\.COM/i, "Shopping"],
  [/AMZN/i, "Shopping"],
  [/BEST BUY/i, "Shopping"],
  [/HOME DEPOT/i, "Shopping"],
  [/LOWE'?S/i, "Shopping"],
  [/IKEA/i, "Shopping"],
  [/VOLSHOP/i, "Shopping"],
  [/GOODWILL/i, "Shopping"],
  [/OFFICE DEPOT/i, "Shopping"],
  [/NORDSTROM/i, "Shopping"],
  [/SAMS PARTY/i, "Shopping"],

  // Utilities
  [/COMCAST/i, "Utilities"],
  [/XFINITY/i, "Utilities"],
  [/AT&?T/i, "Utilities"],
  [/VERIZON/i, "Utilities"],
  [/T-MOBILE/i, "Utilities"],
  [/ELECTRIC/i, "Utilities"],
  [/WATER BILL/i, "Utilities"],
  [/GAS BILL/i, "Utilities"],

  // Health
  [/CVS/i, "Health"],
  [/WALGREENS/i, "Health"],
  [/PHARMACY/i, "Health"],

  // Travel
  [/AIRLINE/i, "Travel"],
  [/DELTA AIR/i, "Travel"],
  [/UNITED AIR/i, "Travel"],
  [/SOUTHWEST/i, "Travel"],
  [/AIRBNB/i, "Travel"],
  [/HOTEL/i, "Travel"],
  [/MARRIOTT/i, "Travel"],
  [/HILTON/i, "Travel"],
  [/AMERICAN 00\d/i, "Travel"],
  [/ALLEGIANT|ALLEGNT/i, "Travel"],
  [/\bAA KIOSK/i, "Travel"],
  [/HOMEWOOD SUITES/i, "Travel"],

  // Transfer / Payment
  [/VENMO/i, "Transfer"],
  [/ONLINE ACH PAYMENT/i, "Transfer"],
  [/REWARD/i, "Transfer"],
  [/PYMT/i, "Transfer"],
  [/ZELLE/i, "Transfer"],
  [/PAYPAL/i, "Transfer"],
  [/CASH APP/i, "Transfer"],

  // Entertainment
  [/TEBEX/i, "Entertainment"],
  [/MODERN WARRIORS/i, "Entertainment"],
  [/CLIMBING/i, "Entertainment"],
  [/PORTLANDROCK/i, "Entertainment"],
  [/MUSEUM/i, "Entertainment"],
  [/UTKATHLETICS/i, "Entertainment"],

  // Rent / Housing
  [/BILT.*RENT/i, "Rent"],
  [/BILTPROTECT/i, "Rent"],

  // Fees
  [/LATE FEE/i, "Fee"],
];
